---
- hosts: all
  remote_user: root
  tasks:
    - name: to install a pkg
      yum:
        name: httpd
        state: latest
    - name: to start the service
      service:
        name: httpd
        state: started
    - name: to configure firewall
      firewalld:
        zone: public
        service: http
        state: enabled
        permanent: yes
        immediate: yes
    - name: to restart the service
      service:
        name: httpd
        state: restarted
                
